apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-be
  namespace: staging
  labels:
    app: mern-be
spec:
  selector:
    matchLabels:
      app: mern-be
  replicas: 1
  template:
    metadata:
      labels:
        app: mern-be
    spec:
      containers:
      - name: mern-be
        image: agambewe/mern-be-staging:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: mern-be-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: mern-be
  ports:
  - port: 4000 
    protocol: "TCP"
